/* eslint-disable @next/next/no-img-element */
import type {Metadata} from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import {checkRole} from "@/utils/roles";
import localFont from "next/font/local";
import Link from "next/link";
import {Menu} from "lucide-react";
import DashboardMenu from "@/components/DashboardMenu";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <nav className="bg-gray-900 text-slate-50">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex items-center justify-between h-16">
                <div className="flex items-center">
                  <Link href="/" className="flex-shrink-0">
                    <div className="rounded-full bg-white h-8 w-8"></div>
                  </Link>
                </div>
                <div className="hidden md:block">
                  <div className="ml-10 flex items-baseline space-x-4 ">
                    <Link
                      href="/"
                      className="hover:bg-gray-700 px-3 py-2 rounded-md "
                    >
                      Home
                    </Link>
                    <Link
                      href="/about"
                      className="hover:bg-gray-700 px-3 py-2 rounded-md"
                    >
                      About
                    </Link>
                    <Link
                      href="/cars"
                      className="hover:bg-gray-700 px-3 py-2 rounded-md "
                    >
                      Cars
                    </Link>
                    <Link
                      href="/pricing"
                      className="hover:bg-gray-700 px-3 py-2 rounded-md "
                    >
                      Pricing
                    </Link>
                    {checkRole("admin") && <DashboardMenu />}
                  </div>
                </div>
                <div className="hidden md:block">
                  <SignedOut>
                    <SignInButton mode="modal">
                      <button className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md text-sm font-medium">
                        Sign In
                      </button>
                    </SignInButton>
                  </SignedOut>
                  <SignedIn>
                    <UserButton />
                  </SignedIn>
                </div>
                <div className="md:hidden flex items-center">
                  <button className="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
                    <span className="sr-only">Open main menu</span>
                    <Menu className="block h-6 w-6" aria-hidden="true" />
                  </button>
                </div>
              </div>
            </div>
            <div className="md:hidden">
              <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
                <Link
                  href="/"
                  className="block hover:bg-gray-700 px-3 py-2 rounded-md text-base font-medium"
                >
                  Home
                </Link>
                <Link
                  href="/about"
                  className="block hover:bg-gray-700 px-3 py-2 rounded-md text-base font-medium"
                >
                  About
                </Link>
                <Link
                  href="/cars"
                  className="block hover:bg-gray-700 px-3 py-2 rounded-md text-base font-medium"
                >
                  Cars
                </Link>
                <Link
                  href="/pricing"
                  className="block hover:bg-gray-700 px-3 py-2 rounded-md text-base font-medium"
                >
                  Pricing
                </Link>
                {checkRole("admin") && (
                  <Link
                    href="/form"
                    className="block hover:bg-gray-700 px-3 py-2 rounded-md text-base font-medium"
                  >
                    Add car
                  </Link>
                )}
              </div>
              <div className="pt-4 pb-3 border-t border-gray-700">
                <div className="flex items-center px-5">
                  <SignedOut>
                    <SignInButton mode="modal">
                      <button className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md text-sm font-medium">
                        Sign In
                      </button>
                    </SignInButton>
                  </SignedOut>
                  <SignedIn>
                    <UserButton afterSignOutUrl="/" />
                  </SignedIn>
                </div>
              </div>
            </div>
          </nav>

          <main>{children}</main>

          <footer className="bg-gray-900 text-white py-8">
            <div className="container mx-auto px-4">
              <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
                <div>
                  <h3 className="text-lg font-semibold mb-4">Sobre nosotros</h3>
                  <p className="text-sm">
                    Somos tu mejor opción para alquilar vehículos de calidad a
                    precios competitivos.
                  </p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-4">
                    Enlaces rápidos
                  </h3>
                  <ul className="text-sm">
                    <li className="mb-2">
                      <a href="#" className="hover:underline">
                        Inicio
                      </a>
                    </li>
                    <li className="mb-2">
                      <a href="#" className="hover:underline">
                        Vehículos
                      </a>
                    </li>
                    <li className="mb-2">
                      <a href="#" className="hover:underline">
                        Reservas
                      </a>
                    </li>
                    <li className="mb-2">
                      <a href="#" className="hover:underline">
                        Contacto
                      </a>
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-4">Contacto</h3>
                  <p className="text-sm mb-2">Teléfono: (123) 456-7890</p>
                  <p className="text-sm mb-2">Email: info@tualquiler.com</p>
                  <p className="text-sm">
                    Dirección: Calle Principal 123, Ciudad
                  </p>
                </div>
                <div>
                  <h3 className="text-lg font-semibold mb-4">Síguenos</h3>
                  <div className="flex space-x-4"></div>
                </div>
              </div>
              <div className="border-t border-gray-700 mt-8 pt-8 text-center text-sm">
                <p>
                  &copy; 2024 Tu Empresa de Alquiler de Autos. Todos los
                  derechos reservados.
                </p>
              </div>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
